2024-10-22 10:54:24,033 WARNING Not Found: /files/15/
2024-10-22 10:54:38,347 WARNING Not Found: /files/upload/
2024-10-22 10:55:10,247 INFO F:\Do_An\web1\web1\settings.py changed, reloading.
2024-10-22 10:55:18,027 WARNING Not Found: /files/upload/
2024-10-22 10:55:52,797 INFO F:\Do_An\web1\web1\urls.py changed, reloading.
2024-10-22 10:56:12,844 INFO Signature generated (hex): 7cedc9bc07cc0f7e522be26c0f1247b22509eb573c3c10eeb1c81605b85f4759c5535d2463bd3dce1e82ca702c7528477a3d9043d1457aefc67bc60f5d01dee423e6ad22d39bed834efdddb2b586c06ece04970d7a153a22ae06112b64c2fdb9d496c48be4d3de8969a5f13da054dbf5a8e06e2383faba03d277ec78577e425a3ac31097f15c117620e53548fd726f4fdd5fc24672b819d04d161728a2da26b686adf8e3d9b743c66427835a4378c990971201df9c181a24b294b1e52328b18bbac6fe95cc18f113bc79a23e8c10d2dda2e446b9b66140c27f3d938c31329ada8e345f6efdd301346c4fd9bbda9c38d548909c88a475999c48164f64c48f1338
2024-10-22 11:18:21,859 INFO Signature generated (hex): 615b2fcdfdcfd28d577d16a49bbc424646622f6e8e2440b131d25dac15d5f061b0428a437c3782fb09e106f18953ee4cb8dcf5f22de1d3d231c2635259c801f4c7082024b445172d704824ead66edda10c7109841cb5f45a4f5bd2f5aef474c3709ce7cfe6a21509415769885b537af9d21f89731f9bdc4792dfe949eda00baacd312ae473920b8bf86cfe08ea6aa6830450a1b6c0a13c4ed373fb4368e73493f3b91848c05c66b21e4627af6f0b3b1b2e5ef5be6715de6a9f6bc4317467f96948639a56b38c4c404e6edceed09446d43fb63efcec97845273f2372cdf71c2a2938359870a2ee69352a2f68739e6921edeb25a03c82e90ac5939e79632d1c478
2024-10-22 13:54:26,593 INFO Signature generated (hex): 5c26de1981b6f2766dd62db7fe5b6b0992f6453e00a301885f6d15142ebae334bcac52fda6a17c774014c31c99df2ebdae80ed7a7eed7d16773bdb479d6dcbc3ba8b6cbbe6c401dcff98c52e25b2159e21073989b88f8918d82b1bad1c6d25eda7cecbd57484155becb738014b6ecfc8413cfa5c8586a56ca8e3359d5bdee6dc71d3baef1a6ee711d6bba45c6bc9d5e9623568bd406eac44d33a7a4c63d008c96ac597c4c788b31d299bd856bb7d9c4c653903ef8f9d517f6acf5dac250014a901cf0fdebb983391e7c938bde9d9a2c1db966866e6cacc6ae96456e6dffd374a2a48fa8f19b6defbd1625606fea7e9bf5d54edcefff5a68a733405a83d419798
2024-10-22 13:56:08,429 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-22 13:56:50,792 INFO Extracted signature text from metadata: 5c26de1981b6f2766dd62db7fe5b6b0992f6453e00a301885f6d15142ebae334bcac52fda6a17c774014c31c99df2ebdae80ed7a7eed7d16773bdb479d6dcbc3ba8b6cbbe6c401dcff98c52e25b2159e21073989b88f8918d82b1bad1c6d25eda7cecbd57484155becb738014b6ecfc8413cfa5c8586a56ca8e3359d5bdee6dc71d3baef1a6ee711d6bba45c6bc9d5e9623568bd406eac44d33a7a4c63d008c96ac597c4c788b31d299bd856bb7d9c4c653903ef8f9d517f6acf5dac250014a901cf0fdebb983391e7c938bde9d9a2c1db966866e6cacc6ae96456e6dffd374a2a48fa8f19b6defbd1625606fea7e9bf5d54edcefff5a68a733405a83d419798
2024-10-22 13:56:51,493 INFO Hash value (hex): dc979d4c2b5db8398edead3b4f58c9915f927dd9fac2d8323e557c5811148e5c
2024-10-22 13:56:51,518 ERROR Signature verification failed: 
2024-10-22 13:58:12,511 INFO Extracted signature text from metadata: 5c26de1981b6f2766dd62db7fe5b6b0992f6453e00a301885f6d15142ebae334bcac52fda6a17c774014c31c99df2ebdae80ed7a7eed7d16773bdb479d6dcbc3ba8b6cbbe6c401dcff98c52e25b2159e21073989b88f8918d82b1bad1c6d25eda7cecbd57484155becb738014b6ecfc8413cfa5c8586a56ca8e3359d5bdee6dc71d3baef1a6ee711d6bba45c6bc9d5e9623568bd406eac44d33a7a4c63d008c96ac597c4c788b31d299bd856bb7d9c4c653903ef8f9d517f6acf5dac250014a901cf0fdebb983391e7c938bde9d9a2c1db966866e6cacc6ae96456e6dffd374a2a48fa8f19b6defbd1625606fea7e9bf5d54edcefff5a68a733405a83d419798
2024-10-22 13:58:13,233 INFO Hash value (hex): dc979d4c2b5db8398edead3b4f58c9915f927dd9fac2d8323e557c5811148e5c
2024-10-22 13:58:13,233 ERROR Signature verification failed: 
2024-10-22 13:59:22,511 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-22 13:59:30,087 INFO Extracted signature text from metadata: 5c26de1981b6f2766dd62db7fe5b6b0992f6453e00a301885f6d15142ebae334bcac52fda6a17c774014c31c99df2ebdae80ed7a7eed7d16773bdb479d6dcbc3ba8b6cbbe6c401dcff98c52e25b2159e21073989b88f8918d82b1bad1c6d25eda7cecbd57484155becb738014b6ecfc8413cfa5c8586a56ca8e3359d5bdee6dc71d3baef1a6ee711d6bba45c6bc9d5e9623568bd406eac44d33a7a4c63d008c96ac597c4c788b31d299bd856bb7d9c4c653903ef8f9d517f6acf5dac250014a901cf0fdebb983391e7c938bde9d9a2c1db966866e6cacc6ae96456e6dffd374a2a48fa8f19b6defbd1625606fea7e9bf5d54edcefff5a68a733405a83d419798
2024-10-22 13:59:30,808 INFO Hash value (hex): dc979d4c2b5db8398edead3b4f58c9915f927dd9fac2d8323e557c5811148e5c
2024-10-22 13:59:30,815 ERROR Signature verification failed: 
2024-10-22 14:00:19,999 INFO Hash value: 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-22 14:00:20,000 INFO Signature generated (hex): 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:02:39,441 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:02:40,163 INFO Hash value (hex): dc979d4c2b5db8398edead3b4f58c9915f927dd9fac2d8323e557c5811148e5c
2024-10-22 14:02:40,163 ERROR Signature verification failed: 
2024-10-22 14:04:20,579 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-22 14:04:25,700 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-22 14:04:32,532 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:04:33,216 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-22 14:04:33,223 INFO Signature verification succeeded.
2024-10-22 14:14:16,517 WARNING Not Found: /file/upload_verification
2024-10-22 14:14:35,255 WARNING Not Found: /file/upload-verify/
2024-10-22 14:15:20,110 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:15:20,859 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-22 14:15:20,860 INFO Signature verification succeeded.
2024-10-22 14:50:37,553 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:50:38,311 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-22 14:50:38,313 INFO Signature verification succeeded.
2024-10-22 14:50:48,079 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:50:48,739 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-22 14:50:48,740 INFO Signature verification succeeded.
2024-10-22 15:16:21,830 WARNING Not Found: /books
2024-10-24 00:17:05,904 WARNING Not Found: /favicon.ico
2024-10-24 00:17:27,603 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-24 00:17:28,627 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-24 00:17:28,642 INFO Signature verification succeeded.
2024-10-25 06:25:01,937 WARNING Not Found: /favicon.ico
2024-10-25 06:33:19,500 WARNING Not Found: /books
2024-10-25 06:34:20,648 WARNING Not Found: /books
2024-10-25 06:34:27,828 WARNING Not Found: /books
2024-10-25 06:38:37,909 WARNING Not Found: /books
2024-10-25 06:38:42,202 WARNING Not Found: /files/uploads
2024-10-25 06:50:51,930 INFO F:\Do_An\web1\file\models.py changed, reloading.
2024-10-25 06:51:00,057 INFO F:\Do_An\web1\file\models.py changed, reloading.
2024-10-25 06:54:19,677 INFO F:\Do_An\web1\file\models.py changed, reloading.
2024-10-25 06:54:43,095 INFO F:\Do_An\web1\file\forms.py changed, reloading.
2024-10-25 06:56:44,159 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-25 06:59:35,700 INFO F:\Do_An\web1\file\models.py changed, reloading.
2024-10-25 07:08:20,903 INFO Key pair found
2024-10-25 07:12:56,624 INFO Key pair found
2024-10-25 07:14:11,110 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-25 15:08:46,842 ERROR Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: baseUser.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\users\views.py", line 52, in user_login
    return render(request, 'users/login.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: baseUser.html
2024-10-25 15:24:15,196 INFO Extracted signature text from metadata: 5c26de1981b6f2766dd62db7fe5b6b0992f6453e00a301885f6d15142ebae334bcac52fda6a17c774014c31c99df2ebdae80ed7a7eed7d16773bdb479d6dcbc3ba8b6cbbe6c401dcff98c52e25b2159e21073989b88f8918d82b1bad1c6d25eda7cecbd57484155becb738014b6ecfc8413cfa5c8586a56ca8e3359d5bdee6dc71d3baef1a6ee711d6bba45c6bc9d5e9623568bd406eac44d33a7a4c63d008c96ac597c4c788b31d299bd856bb7d9c4c653903ef8f9d517f6acf5dac250014a901cf0fdebb983391e7c938bde9d9a2c1db966866e6cacc6ae96456e6dffd374a2a48fa8f19b6defbd1625606fea7e9bf5d54edcefff5a68a733405a83d419798
2024-10-25 15:24:17,361 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-25 15:24:17,476 INFO Signature verification succeeded.
2024-10-25 15:24:29,830 INFO No active key pair found
2024-10-25 15:42:11,572 ERROR Signature verification failed: base.html
2024-10-25 15:42:11,685 ERROR Internal Server Error: /files/upload-verify/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 283, in upload_and_verify
    return render(request, 'files/verify_signature.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
2024-10-25 15:42:24,930 ERROR Signature verification failed: baseFile.html
2024-10-25 15:42:24,966 ERROR Internal Server Error: /files/upload-verify/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: baseFile.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 283, in upload_and_verify
    return render(request, 'files/verify_signature.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: baseFile.html
2024-10-25 15:43:01,875 ERROR Signature verification failed: baseFile.html
2024-10-25 15:43:01,908 ERROR Internal Server Error: /files/upload-verify/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: baseFile.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 283, in upload_and_verify
    return render(request, 'files/verify_signature.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: baseFile.html
2024-10-25 15:44:03,598 ERROR Signature verification failed: files/baseUser.html
2024-10-25 15:44:03,687 ERROR Internal Server Error: /files/upload-verify/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: files/baseUser.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 283, in upload_and_verify
    return render(request, 'files/verify_signature.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: files/baseUser.html
2024-10-25 15:44:35,507 ERROR Internal Server Error: /files/upload-verify/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: files/baseUser.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 287, in upload_and_verify
    return render(request, 'files/verify_signature.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: files/baseUser.html
2024-10-25 15:46:47,023 WARNING Not Found: /carts/view
2024-10-26 07:56:32,391 WARNING Not Found: /favicon.ico
2024-10-26 07:57:43,984 INFO Key pair found
2024-10-26 07:57:57,075 INFO Hash value: e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-10-26 07:57:57,090 INFO Signature generated (hex): 47c1ffe289884a9ececbaa1041cbd25ff1d5395d9a74d3f1c7e2020040366180ef397c033050008c5d38d814fd4e1292ea3875c3ce42da1b9f565986ee83e4e0b5d0cfd6d9cd8390b552faf47765d8ce21a0e4a50c7bd563eef5d179e472cfbf59dbe3a2161e45f0985387dbbf25a044b97cf108f63fc6b4a05ab978aff9f330659e2fa9a25ee77bfb39ab31b63c1044e049d1c110665ee9386070fa4dde7d93c6f60c87904d160662c696bb376544f207d9902475b61b682853cf55d3641fc97cc6c2a8918e4c647e7ba9fe7c19918b97ff93c4adf0eb9a724252d66f33e6c712dc8254352b7770883aa74601490bc94fabb1ddba04f188e5344ef0907ce8b2
2024-10-26 07:59:00,373 WARNING Not Found: /favicon.ico
2024-10-26 07:59:33,523 INFO Extracted signature text from metadata: 47c1ffe289884a9ececbaa1041cbd25ff1d5395d9a74d3f1c7e2020040366180ef397c033050008c5d38d814fd4e1292ea3875c3ce42da1b9f565986ee83e4e0b5d0cfd6d9cd8390b552faf47765d8ce21a0e4a50c7bd563eef5d179e472cfbf59dbe3a2161e45f0985387dbbf25a044b97cf108f63fc6b4a05ab978aff9f330659e2fa9a25ee77bfb39ab31b63c1044e049d1c110665ee9386070fa4dde7d93c6f60c87904d160662c696bb376544f207d9902475b61b682853cf55d3641fc97cc6c2a8918e4c647e7ba9fe7c19918b97ff93c4adf0eb9a724252d66f33e6c712dc8254352b7770883aa74601490bc94fabb1ddba04f188e5344ef0907ce8b2
2024-10-26 07:59:33,894 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-10-26 07:59:33,907 INFO Signature verification succeeded.
2024-10-26 08:02:52,121 INFO Extracted signature text from metadata: 47c1ffe289884a9ececbaa1041cbd25ff1d5395d9a74d3f1c7e2020040366180ef397c033050008c5d38d814fd4e1292ea3875c3ce42da1b9f565986ee83e4e0b5d0cfd6d9cd8390b552faf47765d8ce21a0e4a50c7bd563eef5d179e472cfbf59dbe3a2161e45f0985387dbbf25a044b97cf108f63fc6b4a05ab978aff9f330659e2fa9a25ee77bfb39ab31b63c1044e049d1c110665ee9386070fa4dde7d93c6f60c87904d160662c696bb376544f207d9902475b61b682853cf55d3641fc97cc6c2a8918e4c647e7ba9fe7c19918b97ff93c4adf0eb9a724252d66f33e6c712dc8254352b7770883aa74601490bc94fabb1ddba04f188e5344ef0907ce8b2
2024-10-26 08:02:52,498 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-10-26 08:02:52,499 INFO Signature verification succeeded.
2024-10-26 08:18:08,693 INFO Hash value: 305d107c951de8a54de771d68a786d883b7510eebacfba3d922ede25625be71f
2024-10-26 08:18:08,695 INFO Signature generated (hex): 300d987a3b4e7a433b62df947f34e26d943507fb02e251db413cf56f6bcfd9bdf7991a064b1fd30c7efd08aefb3c55025b7449fa8da4409af222da30f9379497e382c461fe5139cf6a6dcf7d5e8cf23aea21a72c1de4994678cff85e65bbf41009745861b69f717aedaa4842d853ce3397c6c10d56d530f294e8f37b8093292834c151f3199c7ab910a2206468664d0ce1ac135955694cf159392214747e639bbcaccb1375934c754ac60e54b2d0234fd52b5fc5f3a6f1d1f34eb04a61641514e5c904b41049e8278ce3a1cc3cfcd28e47a21879445a8df520d3f6cc7320293deb5aa6630ba78b368139eed480bb13f4f0e123866f1a95d73b63e07da0c5dabc
2024-10-26 08:19:18,996 INFO Key pair found
2024-10-26 08:19:33,383 INFO Hash value: 305d107c951de8a54de771d68a786d883b7510eebacfba3d922ede25625be71f
2024-10-26 08:19:33,385 INFO Signature generated (hex): 82e36ff5333d51b24de957fb42df90bfe26ccd705f6a7d9be1678d3e517897d6e65188236d96734a0e43a5f741fc4942e237fcd485d5027614ccbfe6cbbeba1e9629fe731382c4a04a5631b3e011668bb8911214fefce0c807db29c928f4459cd673b780008dfd37fbcaefce5d07b63f010e624380cb0cb8cc655daf6d74b97ea079af5e9a9125571c5690c49766a1a0fdaf6c604d9f713a88597e450af03d4d642a91cc69d1ce0b75e6a394ddb403fd16aa63c7dd245a7bf304ed89c019998919c83faf957aa170772790f067122a1a41592d06bed91ca26248e5d5f577a8a9e675d77a7da30a94fdeadb44783c3d5fadd311bd7b436474ad262a62666995b4
2024-10-26 08:20:05,042 INFO Extracted signature text from metadata: 300d987a3b4e7a433b62df947f34e26d943507fb02e251db413cf56f6bcfd9bdf7991a064b1fd30c7efd08aefb3c55025b7449fa8da4409af222da30f9379497e382c461fe5139cf6a6dcf7d5e8cf23aea21a72c1de4994678cff85e65bbf41009745861b69f717aedaa4842d853ce3397c6c10d56d530f294e8f37b8093292834c151f3199c7ab910a2206468664d0ce1ac135955694cf159392214747e639bbcaccb1375934c754ac60e54b2d0234fd52b5fc5f3a6f1d1f34eb04a61641514e5c904b41049e8278ce3a1cc3cfcd28e47a21879445a8df520d3f6cc7320293deb5aa6630ba78b368139eed480bb13f4f0e123866f1a95d73b63e07da0c5dabc
2024-10-26 08:20:05,048 INFO Hash value (hex): 305d107c951de8a54de771d68a786d883b7510eebacfba3d922ede25625be71f
2024-10-26 08:20:05,049 INFO Signature verification succeeded.
2024-10-26 08:20:56,402 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-26 08:21:43,367 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-26 08:21:51,909 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-26 08:22:22,597 INFO Key pair found
2024-10-26 08:22:27,235 INFO Hash value: 305d107c951de8a54de771d68a786d883b7510eebacfba3d922ede25625be71f
2024-10-26 08:22:27,238 INFO Signature generated (hex): 5b9c2cc664b6d3c60d5dba41966f5e4bef2c2a2b4bfd3c0ede18a2aec14feaa75f6ba7dde7b947f8c7db743833cd86632327d0470b998f580ec78ad50b5bd0fe02795dcd3929d9aca1faba70adfe3452fab71dc71c0b3c5aa481fc7d2d25502b52b971cdd38670eb0fd0e1066fe927d43389837d1974aa23ccacf53af2e165b4a856aed670f17338ccd1c26de83c64921dc6f1304bf8c4b0a38554aae0538b75772a93f49fb9c1ba51072cc1f152af5d3fbc16a005c77b6740f3c1f7150e6e5e5a0a436efadb20de21ddabccf90783d43e9ab403d0bed2e256788a64fd6260cf856785497002488ba4be53d1bab1d6f3b2a08bbc9c23af3cce09991c3a5c688b
2024-10-26 22:54:47,409 WARNING Not Found: /favicon.ico
2024-10-26 22:56:29,695 INFO Key pair found
2024-10-27 15:05:05,025 WARNING Not Found: /favicon.ico
2024-10-27 15:10:42,647 WARNING Not Found: /image1.jpg
2024-10-27 15:10:42,650 WARNING Not Found: /image2.jpg
2024-10-27 15:10:42,688 WARNING Not Found: /image3.jpg
2024-10-27 15:10:42,695 WARNING Not Found: /script.js
2024-10-27 15:12:44,159 WARNING Not Found: /img/image1.jpg
2024-10-27 15:12:44,167 WARNING Not Found: /image2.jpg
2024-10-27 15:12:44,208 WARNING Not Found: /image3.jpg
2024-10-27 15:12:44,213 WARNING Not Found: /script.js
2024-10-27 15:12:45,508 WARNING Not Found: /img/image1.jpg
2024-10-27 15:12:45,512 WARNING Not Found: /image2.jpg
2024-10-27 15:12:45,553 WARNING Not Found: /image3.jpg
2024-10-27 15:12:45,559 WARNING Not Found: /script.js
2024-10-27 15:13:06,860 WARNING Not Found: /img/image1.jpg
2024-10-27 15:13:06,864 WARNING Not Found: /image2.jpg
2024-10-27 15:13:06,906 WARNING Not Found: /image3.jpg
2024-10-27 15:13:06,911 WARNING Not Found: /script.js
2024-10-27 15:13:08,111 WARNING Not Found: /img/image1.jpg
2024-10-27 15:13:08,116 WARNING Not Found: /image2.jpg
2024-10-27 15:13:08,159 WARNING Not Found: /image3.jpg
2024-10-27 15:13:08,163 WARNING Not Found: /script.js
2024-10-27 15:13:58,030 INFO F:\Do_An\web1\home\urls.py changed, reloading.
2024-10-27 15:16:29,711 WARNING Not Found: /img/image1.jpg
2024-10-27 15:16:29,765 WARNING Not Found: /img/image1.jpg
2024-10-27 15:18:33,031 WARNING Not Found: /img/image1.jpg
2024-10-27 15:18:33,370 WARNING Not Found: /img/image1.jpg
2024-10-27 15:18:34,459 WARNING Not Found: /img/image1.jpg
2024-10-27 15:18:34,506 WARNING Not Found: /img/image1.jpg
2024-10-27 15:18:41,877 WARNING Not Found: /img/image1.jpg
2024-10-27 15:18:41,929 WARNING Not Found: /img/image1.jpg
2024-10-27 15:19:03,232 WARNING Not Found: /img/image1.jpg
2024-10-27 15:19:03,280 WARNING Not Found: /img/image1.jpg
2024-10-27 15:19:05,551 WARNING Not Found: /img/image1.jpg
2024-10-27 15:19:05,611 WARNING Not Found: /img/image1.jpg
2024-10-27 15:19:13,923 WARNING Not Found: /img/image1.jpg
2024-10-27 15:19:13,981 WARNING Not Found: /img/image1.jpg
2024-10-27 15:19:15,131 WARNING Not Found: /img/image1.jpg
2024-10-27 15:19:15,188 WARNING Not Found: /img/image1.jpg
2024-10-27 15:20:08,068 WARNING Not Found: /img/image1.jpg
2024-10-27 15:20:08,401 WARNING Not Found: /img/image1.jpg
2024-10-27 15:22:03,449 WARNING Not Found: /favicon.ico
2024-10-27 15:28:39,873 WARNING Not Found: /image1.jpg
2024-10-27 15:28:39,881 WARNING Not Found: /image2.jpg
2024-10-27 15:28:40,006 WARNING Not Found: /image3.jpg
2024-10-27 15:29:01,614 WARNING Not Found: /image2.jpg
2024-10-27 15:29:01,621 WARNING Not Found: /image3.jpg
2024-10-27 15:29:17,083 WARNING Not Found: /image2.jpg
2024-10-27 15:29:17,097 WARNING Not Found: /image3.jpg
2024-10-27 15:36:22,955 WARNING Not Found: /image1.jpg
2024-10-27 15:36:22,963 WARNING Not Found: /image2.jpg
2024-10-27 15:36:23,098 WARNING Not Found: /image3.jpg
2024-10-27 15:37:03,726 WARNING Not Found: /image2.jpg
2024-10-27 15:37:03,731 WARNING Not Found: /image3.jpg
2024-10-27 16:00:02,661 WARNING Not Found: /img_snowtops.jpg
2024-10-27 16:00:02,685 WARNING Not Found: /img_lights.jpg
2024-10-27 16:00:02,852 WARNING Not Found: /img_mountains.jpg
2024-10-27 16:00:02,858 WARNING Not Found: /img_forest.jpg
2024-10-27 16:00:20,072 WARNING Not Found: /img_lights.jpg
2024-10-27 16:00:20,249 WARNING Not Found: /img_mountains.jpg
2024-10-27 16:00:20,258 WARNING Not Found: /img_forest.jpg
2024-10-27 16:03:23,595 WARNING Not Found: /img_nature_wide.jpg
2024-10-27 16:03:23,603 WARNING Not Found: /img_snow_wide.jpg
2024-10-27 16:03:24,817 WARNING Not Found: /img_mountains_wide.jpg
2024-10-27 16:14:25,992 ERROR Internal Server Error: /files/download/15/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 182, in download_file
    signature = gen_sig(key_pair, file)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 143, in gen_sig
    keypair.private_key.encode('utf-8'),
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'private_key'
2024-10-27 21:28:22,074 WARNING Not Found: /favicon.ico
2024-10-27 21:29:36,689 INFO Key pair found
2024-10-27 22:11:48,731 INFO Hash value: e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-10-27 22:11:48,735 INFO Signature generated (hex): 1e462537c703a2ee051cf87f299d44ad2006d629b2607805b65e61789b4ff4548637e137c995956afeaaf4621bb232def4228bde57956c3bc1b5a415ceba78a6f369de7db547bd43c4658eff43e3e7270401058ea848644030abe171869719511b981c7df52cbd11ad74bd34827034552066ca6c3a1238aa57f9a5ff2cb860161048bd5c9bc56914bb559d466c9f6057f26dc2a10f624cc07d991f66003cebbf57e5910bc46b620c8fe299b7f729cf8eb606fad2d98fedf3062003578a631ce4a9884cf84c57c82fbb9edf81c5fba8aec29d290824fb4fb8715a617c571c4bd6876842fa576f9f336ae921daa96e831273d1162a6f5f1e53f669c79b33fe6f47
2024-10-27 22:17:29,411 ERROR Internal Server Error: /files/status/all/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "request.GET.get('order')"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 71, in list_files_by_status
    return render(request, 'files/file_list.html', {'files': files, 'status': status})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('order')' from 'request.GET.get('order')'
2024-10-28 06:48:48,334 WARNING Not Found: /favicon.ico
2024-10-28 06:48:53,170 WARNING Not Found: /files/status/all/
2024-10-28 06:49:10,340 INFO F:\Do_An\web1\file\urls.py changed, reloading.
2024-10-28 06:49:32,072 WARNING Not Found: /files/status/all/
2024-10-28 06:52:01,842 WARNING Not Found: /files/status/all/
2024-10-28 07:50:13,355 INFO Key pair found
2024-10-28 07:52:00,061 INFO Key pair found
2024-10-28 07:54:08,760 WARNING Not Found: /files/status/all/
2024-10-28 07:54:23,924 WARNING Not Found: /files/status/all/
2024-10-28 07:54:24,694 WARNING Not Found: /files/status/all/
2024-10-28 08:12:15,867 INFO Key pair found
2024-10-28 08:28:02,911 INFO Key pair found
2024-10-28 08:28:28,920 INFO Key pair found
2024-10-28 08:28:31,814 INFO Key pair found
2024-10-28 08:29:07,455 INFO Key pair found
2024-10-28 08:30:25,250 INFO Key pair found
2024-10-28 08:30:48,509 INFO Key pair found
2024-10-28 08:30:57,607 INFO Key pair found
2024-10-28 08:33:02,234 INFO Key pair found
2024-10-28 08:33:31,630 INFO Key pair found
2024-10-28 08:34:23,639 INFO Key pair found
2024-10-28 08:35:59,660 INFO Key pair found
2024-10-28 08:38:47,118 INFO Key pair found
2024-10-28 08:39:06,845 INFO Key pair found
2024-10-28 08:40:43,006 INFO Key pair found
2024-10-28 08:42:14,247 INFO Key pair found
2024-10-28 09:19:45,467 WARNING Not Found: /favicon.ico
2024-10-28 09:21:07,062 INFO Key pair found
2024-10-28 09:21:29,629 INFO Key pair found
2024-10-28 09:21:46,477 INFO Key pair found
2024-10-28 09:22:38,350 INFO Key pair found
2024-10-28 09:22:44,722 INFO Key pair found
2024-10-28 09:23:00,702 INFO Key pair found
2024-10-28 09:23:48,806 INFO Key pair found
2024-10-28 09:42:55,592 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-10-28 09:42:55,672 INFO Signature verification succeeded.
2024-10-28 09:46:39,982 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-10-28 09:46:39,982 INFO Signature verification succeeded.
2024-10-28 09:46:46,439 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-10-28 09:46:46,440 INFO Signature verification succeeded.
2024-10-28 09:46:56,590 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-28 09:46:56,591 INFO Signature verification succeeded.
2024-10-28 10:31:51,271 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-29 05:18:54,471 WARNING Not Found: /favicon.ico
2024-10-29 05:18:55,838 INFO Key pair found
2024-10-29 05:18:55,931 ERROR Internal Server Error: /files/15/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 63, in view_file
    return render(request, 'files/file_detail.html', {'file_url': file_url, 'file_obj': file_obj})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
2024-10-29 05:19:15,756 INFO Key pair found
2024-10-29 05:20:33,589 INFO F:\Do_An\web1\picture\views.py changed, reloading.
2024-10-29 05:20:48,705 INFO Key pair found
2024-10-29 05:20:51,908 ERROR Internal Server Error: /pictures/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\picture\views.py", line 10, in get_all_pictures
    return render(request, 'files/file_detail.html', {'pictures': pictures})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'download_file' with arguments '('',)' not found. 1 pattern(s) tried: ['files/download/(?P<file_id>[0-9]+)/\\Z']
2024-10-29 05:21:21,068 INFO F:\Do_An\web1\picture\views.py changed, reloading.
2024-10-29 05:22:05,797 INFO F:\Do_An\web1\picture\models.py changed, reloading.
2024-10-29 05:23:23,201 INFO F:\Do_An\web1\picture\forms.py changed, reloading.
2024-10-29 05:23:38,597 INFO F:\Do_An\web1\picture\forms.py changed, reloading.
2024-10-29 05:25:31,026 DEBUG STREAM b'IHDR' 16 13
2024-10-29 05:25:31,026 DEBUG STREAM b'pHYs' 41 9
2024-10-29 05:25:31,026 DEBUG STREAM b'tEXt' 62 25
2024-10-29 05:25:31,026 DEBUG STREAM b'IDAT' 99 8192
2024-10-29 05:25:31,026 DEBUG Importing BlpImagePlugin
2024-10-29 05:25:31,029 DEBUG Importing BmpImagePlugin
2024-10-29 05:25:31,030 DEBUG Importing BufrStubImagePlugin
2024-10-29 05:25:31,031 DEBUG Importing CurImagePlugin
2024-10-29 05:25:31,033 DEBUG Importing DcxImagePlugin
2024-10-29 05:25:31,035 DEBUG Importing DdsImagePlugin
2024-10-29 05:25:31,038 DEBUG Importing EpsImagePlugin
2024-10-29 05:25:31,040 DEBUG Importing FitsImagePlugin
2024-10-29 05:25:31,041 DEBUG Importing FliImagePlugin
2024-10-29 05:25:31,042 DEBUG Importing FpxImagePlugin
2024-10-29 05:25:31,043 DEBUG Image: failed to import FpxImagePlugin: No module named 'olefile'
2024-10-29 05:25:31,043 DEBUG Importing FtexImagePlugin
2024-10-29 05:25:31,044 DEBUG Importing GbrImagePlugin
2024-10-29 05:25:31,045 DEBUG Importing GifImagePlugin
2024-10-29 05:25:31,046 DEBUG Importing GribStubImagePlugin
2024-10-29 05:25:31,047 DEBUG Importing Hdf5StubImagePlugin
2024-10-29 05:25:31,049 DEBUG Importing IcnsImagePlugin
2024-10-29 05:25:31,053 DEBUG Importing IcoImagePlugin
2024-10-29 05:25:31,054 DEBUG Importing ImImagePlugin
2024-10-29 05:25:31,056 DEBUG Importing ImtImagePlugin
2024-10-29 05:25:31,057 DEBUG Importing IptcImagePlugin
2024-10-29 05:25:31,059 DEBUG Importing JpegImagePlugin
2024-10-29 05:25:31,059 DEBUG Importing Jpeg2KImagePlugin
2024-10-29 05:25:31,059 DEBUG Importing McIdasImagePlugin
2024-10-29 05:25:31,060 DEBUG Importing MicImagePlugin
2024-10-29 05:25:31,061 DEBUG Image: failed to import MicImagePlugin: No module named 'olefile'
2024-10-29 05:25:31,062 DEBUG Importing MpegImagePlugin
2024-10-29 05:25:31,063 DEBUG Importing MpoImagePlugin
2024-10-29 05:25:31,069 DEBUG Importing MspImagePlugin
2024-10-29 05:25:31,071 DEBUG Importing PalmImagePlugin
2024-10-29 05:25:31,075 DEBUG Importing PcdImagePlugin
2024-10-29 05:25:31,076 DEBUG Importing PcxImagePlugin
2024-10-29 05:25:31,077 DEBUG Importing PdfImagePlugin
2024-10-29 05:25:31,084 DEBUG Importing PixarImagePlugin
2024-10-29 05:25:31,086 DEBUG Importing PngImagePlugin
2024-10-29 05:25:31,086 DEBUG Importing PpmImagePlugin
2024-10-29 05:25:31,086 DEBUG Importing PsdImagePlugin
2024-10-29 05:25:31,087 DEBUG Importing QoiImagePlugin
2024-10-29 05:25:31,089 DEBUG Importing SgiImagePlugin
2024-10-29 05:25:31,090 DEBUG Importing SpiderImagePlugin
2024-10-29 05:25:31,092 DEBUG Importing SunImagePlugin
2024-10-29 05:25:31,093 DEBUG Importing TgaImagePlugin
2024-10-29 05:25:31,094 DEBUG Importing TiffImagePlugin
2024-10-29 05:25:31,094 DEBUG Importing WebPImagePlugin
2024-10-29 05:25:31,102 DEBUG Importing WmfImagePlugin
2024-10-29 05:25:31,104 DEBUG Importing XbmImagePlugin
2024-10-29 05:25:31,105 DEBUG Importing XpmImagePlugin
2024-10-29 05:25:31,106 DEBUG Importing XVThumbImagePlugin
2024-10-29 05:32:42,979 DEBUG STREAM b'IHDR' 16 13
2024-10-29 05:32:42,979 DEBUG STREAM b'sRGB' 41 1
2024-10-29 05:32:42,980 DEBUG STREAM b'gAMA' 54 4
2024-10-29 05:32:42,980 DEBUG STREAM b'pHYs' 70 9
2024-10-29 05:32:42,980 DEBUG STREAM b'IDAT' 91 42131
2024-10-29 05:46:09,805 INFO Key pair found
2024-10-29 06:02:22,400 INFO Key pair found
2024-10-29 06:02:53,207 INFO Key pair found
2024-10-29 06:02:53,240 ERROR Internal Server Error: /files/15/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 63, in view_file
    return render(request, 'files/file_detail.html', {'file_url': file_url, 'file_obj': file_obj})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
2024-10-29 06:03:00,516 INFO Key pair found
2024-10-29 06:03:00,545 ERROR Internal Server Error: /files/15/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 63, in view_file
    return render(request, 'files/file_detail.html', {'file_url': file_url, 'file_obj': file_obj})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
2024-10-29 06:03:10,311 INFO Key pair found
2024-10-29 06:03:10,339 ERROR Internal Server Error: /files/15/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 63, in view_file
    return render(request, 'files/file_detail.html', {'file_url': file_url, 'file_obj': file_obj})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
2024-10-29 06:03:10,950 INFO Key pair found
2024-10-29 06:03:10,978 ERROR Internal Server Error: /files/15/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 63, in view_file
    return render(request, 'files/file_detail.html', {'file_url': file_url, 'file_obj': file_obj})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
2024-10-29 06:03:28,165 INFO Key pair found
2024-10-29 06:06:02,362 INFO Key pair found
2024-10-29 06:06:13,608 INFO Key pair found
2024-10-29 06:06:25,732 INFO Key pair found
2024-10-29 06:06:55,567 INFO Key pair found
2024-10-29 06:07:05,621 INFO Key pair found
2024-10-29 06:08:57,185 INFO Key pair found
2024-10-29 06:09:24,166 INFO Key pair found
2024-10-29 06:10:48,762 INFO Key pair found
2024-10-29 06:11:13,899 INFO Key pair found
2024-10-29 06:14:39,447 INFO Key pair found
2024-10-29 06:21:05,218 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-29 06:21:45,640 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-29 06:22:00,052 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-29 06:22:04,809 INFO Key pair found
2024-10-29 06:22:32,057 INFO Key pair found
2024-10-29 06:22:50,455 INFO Key pair found
2024-10-29 06:23:09,545 INFO Key pair found
2024-10-29 06:25:29,055 INFO Key pair found
2024-10-29 06:29:23,843 INFO Key pair found
2024-10-29 07:11:34,538 WARNING Not Found: /favicon.ico
2024-10-29 07:14:08,675 ERROR No active key pair found
2024-10-30 19:32:44,797 WARNING Not Found: /favicon.ico
2024-10-30 19:33:36,168 INFO Key pair found
2024-10-30 19:34:12,585 INFO Key pair found
2024-10-30 19:39:37,126 INFO Key pair found
2024-10-30 19:58:07,151 WARNING Not Found: /home/static/home/logo.png
2024-10-30 19:58:22,193 WARNING Not Found: /home/static/home/logo.png
2024-10-31 14:30:40,684 WARNING Not Found: /favicon.ico
2024-10-31 20:12:09,648 WARNING Not Found: /favicon.ico
2024-10-31 22:04:10,060 WARNING Not Found: /accounts/login/
2024-11-01 10:48:54,259 WARNING Not Found: /favicon.ico
2024-11-01 10:49:06,439 ERROR No active key pair found
2024-11-01 10:52:48,490 ERROR No active key pair found
2024-11-01 11:01:00,383 INFO Key pair found
2024-11-01 11:01:26,543 INFO Key pair found
2024-11-01 11:02:03,937 INFO Key pair found
2024-11-03 11:32:08,934 WARNING Not Found: /favicon.ico
2024-11-03 11:32:24,526 INFO Key pair found
2024-11-03 11:32:37,631 INFO Hash value: e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 11:32:37,646 INFO Signature generated (hex): 49591c53bc96567187a1df22a1f3dd8d684812904277a6bdb9b9281c17b1f1941cb9c85aecaa43392029ba7b73267262d14027a0e28c64b739f3cada46e43656fbd12eb34b323fd389662a6314450ce818f8f3ec446f68cdf59c59d2378ef1ed4544918c19ec2b8eba9938c7a0340a298ac047e6f596cca1e9e511d79333a6f30260cc96f0ad0bc2531891f249ab03a86a490762f02f41a2ee458a4b0f583713cf1f57b3d8f0184b8b1eb18ef5a353687e5e2eafd76e592bde628e297c27bd06944466832549c7e9ff523f0f7845720d12e8022d6b4d76d8a7af69716c0cdaacb60ed6dd5edd0224b709c04011dab0cf48e6498a9023a993fe7e9cb749969436
2024-11-03 11:34:12,453 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 11:34:12,461 INFO Signature verification succeeded.
2024-11-03 11:48:11,003 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-03 11:51:29,917 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 11:51:29,958 INFO Signature verification succeeded.
2024-11-03 11:52:08,163 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 11:52:08,164 INFO Signature verification succeeded.
2024-11-03 11:55:05,574 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 11:55:05,576 INFO Signature verification succeeded.
2024-11-03 12:00:56,464 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:00:56,466 INFO Signature verification succeeded.
2024-11-03 12:21:07,110 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-03 12:22:32,340 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-03 12:25:44,111 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-03 12:26:31,739 INFO Signature verification succeeded.
2024-11-03 12:26:32,857 WARNING Not Found: /media/4b127ebf38f947f490cddf4b40b2d76e_44daki.pdf
2024-11-03 12:26:43,010 INFO Signature verification succeeded.
2024-11-03 12:26:43,507 WARNING Not Found: /media/c2230cc89c7d483a91bf2891319746e7_44daki.pdf
2024-11-03 12:26:46,399 WARNING Not Found: /media/4b127ebf38f947f490cddf4b40b2d76e_44daki.pdf
2024-11-03 12:26:57,706 INFO Signature verification succeeded.
2024-11-03 12:27:06,099 INFO Signature verification succeeded.
2024-11-03 12:27:17,670 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-03 12:31:21,156 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:31:21,173 INFO Signature verification succeeded.
2024-11-03 12:33:35,919 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:33:35,920 INFO Signature verification succeeded.
2024-11-03 12:34:03,092 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:34:03,092 INFO Signature verification succeeded.
2024-11-03 12:34:44,467 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:34:44,468 INFO Signature verification succeeded.
2024-11-03 12:36:19,473 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:36:19,475 INFO Signature verification succeeded.
2024-11-03 12:37:37,818 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:37:37,819 INFO Signature verification succeeded.
2024-11-03 12:39:20,728 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:39:20,730 INFO Signature verification succeeded.
2024-11-03 12:39:52,886 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:39:52,887 INFO Signature verification succeeded.
2024-11-03 12:39:53,293 ERROR Internal Server Error: /files/upload-verify/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 237, in upload_and_verify
    return render(request, 'files/verify_signature.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' + user_profile.user.first_name' from 'user_profile.user.last_name + user_profile.user.first_name'
2024-11-03 12:40:28,111 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:40:28,112 INFO Signature verification succeeded.
2024-11-03 12:41:06,776 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:41:06,776 INFO Signature verification succeeded.
2024-11-03 12:41:19,559 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 12:41:19,560 INFO Signature verification succeeded.
2024-11-03 15:10:59,451 INFO Key pair found
2024-11-03 15:12:34,688 INFO Key pair found
2024-11-03 15:12:34,760 ERROR Internal Server Error: /files/15/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: baseFire.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 68, in view_file
    return render(request, 'files/file_detail.html', {'file_url': file_url, 'file_obj': file_obj,'picture':picture})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: baseFire.html
2024-11-03 15:12:52,481 INFO Key pair found
2024-11-03 15:12:52,549 ERROR Internal Server Error: /files/15/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: files/baseFire.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 68, in view_file
    return render(request, 'files/file_detail.html', {'file_url': file_url, 'file_obj': file_obj,'picture':picture})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: files/baseFire.html
2024-11-03 15:13:04,692 INFO Key pair found
2024-11-03 15:13:08,964 INFO Key pair found
2024-11-03 15:14:02,968 INFO Key pair found
2024-11-03 15:14:36,318 INFO Key pair found
2024-11-03 15:14:57,223 INFO Key pair found
2024-11-03 15:15:21,837 INFO Key pair found
2024-11-03 15:16:25,171 INFO Key pair found
2024-11-03 15:18:55,340 INFO Key pair found
2024-11-03 15:19:23,454 INFO Key pair found
2024-11-03 15:21:36,724 INFO Key pair found
2024-11-03 15:22:48,031 INFO Key pair found
2024-11-03 15:23:33,441 INFO Key pair found
2024-11-03 15:24:44,815 INFO Key pair found
2024-11-03 15:27:54,977 INFO Key pair found
2024-11-03 15:29:37,200 INFO Key pair found
2024-11-03 15:30:01,245 INFO Key pair found
2024-11-03 15:30:49,374 INFO Key pair found
2024-11-03 19:51:33,793 WARNING Not Found: /favicon.ico
2024-11-03 19:51:45,426 INFO Key pair found
2024-11-03 19:56:43,113 INFO F:\Do_An\web1\users\forms.py changed, reloading.
2024-11-03 19:58:08,461 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 19:58:08,491 INFO Signature verification succeeded.
2024-11-03 20:00:53,823 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-03 20:01:53,170 INFO Key pair found
2024-11-03 20:04:26,646 INFO Key pair found
2024-11-03 20:06:59,501 INFO Key pair found
2024-11-03 20:12:44,741 INFO Key pair found
2024-11-03 20:12:52,289 INFO Key pair found
2024-11-03 20:13:59,358 INFO Key pair found
2024-11-03 20:14:16,742 INFO Key pair found
2024-11-03 20:14:40,344 INFO Key pair found
2024-11-03 20:17:13,291 INFO Key pair found
2024-11-03 20:18:16,331 INFO Key pair found
2024-11-03 20:19:24,092 INFO Key pair found
2024-11-03 20:20:54,322 INFO Key pair found
2024-11-03 20:20:54,706 ERROR Internal Server Error: /files/19/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 68, in view_file
    return render(request, 'files/file_detail.html', {'file_url': file_url, 'file_obj': file_obj,'picture':picture})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0].img_path.url' from 'pic[0].img_path.url'
2024-11-03 20:21:16,417 INFO Key pair found
2024-11-03 20:21:16,515 ERROR Internal Server Error: /files/19/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 68, in view_file
    return render(request, 'files/file_detail.html', {'file_url': file_url, 'file_obj': file_obj,'picture':picture})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0].img_path.url' from 'picture[0].img_path.url'
2024-11-03 20:21:52,674 INFO Key pair found
2024-11-03 20:23:55,410 INFO Key pair found
2024-11-03 20:24:27,544 INFO Key pair found
2024-11-03 20:30:01,030 INFO Key pair found
2024-11-03 20:33:41,326 INFO Key pair found
2024-11-03 20:38:15,994 INFO Key pair found
2024-11-03 20:38:45,164 INFO Key pair found
2024-11-03 20:41:11,915 INFO Key pair found
2024-11-03 20:41:48,203 INFO Key pair found
2024-11-03 20:42:26,468 INFO Key pair found
2024-11-03 20:42:46,793 INFO Key pair found
2024-11-03 20:42:52,384 INFO Key pair found
2024-11-03 20:43:03,755 INFO Key pair found
2024-11-03 20:46:32,444 INFO Key pair found
2024-11-03 20:46:47,114 INFO Key pair found
2024-11-03 20:46:58,639 INFO Key pair found
2024-11-03 20:47:09,824 INFO Key pair found
2024-11-03 20:50:43,457 INFO Key pair found
2024-11-03 20:51:42,009 INFO Key pair found
2024-11-03 20:52:10,925 INFO Key pair found
2024-11-03 20:52:29,479 INFO Key pair found
2024-11-03 20:53:04,559 INFO Key pair found
2024-11-03 20:53:27,303 INFO Key pair found
2024-11-03 20:53:41,195 INFO Key pair found
2024-11-03 20:55:46,250 INFO Key pair found
2024-11-03 21:17:47,921 INFO Key pair found
2024-11-03 21:18:06,483 INFO Key pair found
2024-11-03 21:19:59,312 INFO Key pair found
2024-11-03 21:20:21,318 INFO Key pair found
2024-11-03 21:25:25,082 INFO Key pair found
2024-11-03 21:26:02,289 INFO Key pair found
2024-11-03 21:27:38,534 INFO Key pair found
2024-11-03 21:31:35,869 INFO Key pair found
2024-11-03 21:31:54,967 INFO Key pair found
2024-11-03 21:32:45,988 INFO Key pair found
2024-11-03 21:32:57,833 INFO Key pair found
2024-11-03 21:36:12,700 INFO Key pair found
2024-11-03 21:36:52,768 INFO Hash value: e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-11-03 21:36:52,772 INFO Signature generated (hex): 4bbb3200e795823b1cb76d500f131487c4bf5d2ee805816eca3a7e88436d2e191fd76ecec7eafef929417b836fcc645c4b8c22de6411452ef7df33e24db06e5c7e348c09c44eeab5b75c6790e43030e87213a97a9fca2b58b9f103061c3062cf396bdbe119d484bc6aca582dfd367fc98e7aff7c2dfe41e59e170d15c5e6f6dc2f5431af75c4616ec8ed559ddb257d01a7f7e681440ee5fa3a4395df5331b5caa1d7679536f1e7e866e55664b8fe10b47a4d5e14a38f6369a3b10f04571a02994fcd2902a0828b3c002a4c19c255f085aa8a25b3a810ce3388bdc2ad7d3deb287600fc858553b6454c550265989fcc4310c23cdcdbac6169e3654bb6189927e6
2024-11-03 21:37:20,344 INFO Key pair found
2024-11-05 11:56:42,585 INFO Key pair found
2024-11-05 11:56:44,410 ERROR Internal Server Error: /files/download/39/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 134, in download_file
    signature = gen_sig(key_pair, file)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 101, in gen_sig
    reader = PdfReader(file.file_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyPDF2\_reader.py", line 319, in __init__
    self.read(stream)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyPDF2\_reader.py", line 1414, in read
    self._basic_validation(stream)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyPDF2\_reader.py", line 1453, in _basic_validation
    stream.seek(0, os.SEEK_END)
    ^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\utils.py", line 45, in <lambda>
    seek = property(lambda self: self.file.seek)
                                 ^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\files.py", line 51, in _get_file
    self._file = self.storage.open(self.name, "rb")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\storage\base.py", line 22, in open
    return self._open(name, mode)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\files\storage\filesystem.py", line 81, in _open
    return File(open(self.path(name), mode))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Do_An\\web1\\media\\uploads\\file1.pdf'
2024-11-05 11:57:07,901 INFO Key pair found
2024-11-05 11:57:13,333 INFO Hash value: 5c1f2b99a52da80e9554d100a69148495f4fe48741d3e044155aa41b689c9612
2024-11-05 11:57:13,334 INFO Signature generated (hex): 7221c7392015838f2f000398b1e6d7a2dbc85d1e7d0426c5245bf381ba35408bfc0d7a61ba8c4529d1a4518f5284f973b868a779653d4bb1ee562529397967fa90a3703cc93082bcbaac43c1a844020ecf82316c5db4136ef4c504761ab43ae11cdbd12104a0933b5dcd9107f4be1883d7c5052353762b9564985f25f47f5d158acdee21503ef93dd41363abb56c53b7add025cbca97b3edc835488d4a7f3a52c8b909969c63c9a6f90cf7defdda6806d8cd772af2751db916ff631f07826cccdf1b15757b7dfad625301671a989d20202762bff584bca47d9443d9ecfa734be69cca566cfac4944211c1100a2aafde3e6d2869baa0317cd1ba6601396d176d9
2024-11-05 11:57:41,613 INFO Hash value (hex): 5c1f2b99a52da80e9554d100a69148495f4fe48741d3e044155aa41b689c9612
2024-11-05 11:57:41,614 INFO Signature verification succeeded.
2024-11-05 13:06:26,188 INFO Hash value: 043ced84df5acce2195f76fc56c1c321edf5317b629008ec9b765baaf29725fa
2024-11-05 13:06:26,189 INFO Signature generated (hex): 811a07ed6979b9154f66e99851d57c66d5265e655e1c72e0ba726a1860cf1a72f720f5339d564c00a5d72082a25835129432d7027624d55f33ebd56ac2b6e82d06402339c3a6c0a75b630dbf714dee97cd944e3869850f209379d87f101b1ee6c3e58b0418169a2e4556417b1cf7142875b97e9624071745287559390acb799a1ecf091e09a9335ca2f5bbfcf9d87672cecb183a29ff3a288ce8984f8a6d3f62f5e0e1c4b324e26d4aeca3e19777a5661a094b457ec2e0f4602b216b2c645f66ed45eca6e54dd668041320d5a04381641c8bd6ecbb24bfef7223e6527a186981ee595e345dc5e42e8a03fd453201063fd655863d50fcdf73a51752b3bcee18b5
2024-11-05 13:06:43,044 INFO Hash value (hex): 043ced84df5acce2195f76fc56c1c321edf5317b629008ec9b765baaf29725fa
2024-11-05 13:06:43,045 INFO Signature verification succeeded.
2024-11-05 13:15:32,727 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 15:01:51,028 WARNING Not Found: /favicon.ico
2024-11-06 21:44:02,727 WARNING Not Found: /favicon.ico
2024-11-06 21:50:23,598 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 21:50:48,554 INFO Hash value (hex): 043ced84df5acce2195f76fc56c1c321edf5317b629008ec9b765baaf29725fa
2024-11-06 21:50:48,571 ERROR Signature verification failed: 
2024-11-06 22:18:06,728 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:18:13,959 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:19:29,566 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:19:59,179 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:20:02,868 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:20:18,935 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:20:36,055 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:25:29,339 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:26:00,445 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:26:28,252 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:26:39,478 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:27:29,457 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:28:55,081 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:29:05,055 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:29:14,030 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:30:49,082 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:31:06,638 ERROR Internal Server Error: /files/download/41/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 166, in download_file
    signature = gen_sig(key_pair, file)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 98, in gen_sig
    keypair.private_key.encode('utf-8'),
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'private_key'
2024-11-06 22:32:37,125 INFO Hash value: aa339cad51a6da1fb89278882b482e200760dbf9474c2267de8a25e7f1afb483
2024-11-06 22:32:37,133 INFO Signature generated (hex): 093b160aaf15b95d5e47d01248454ba227e497dc5f8b2890696dfc7ff9581416f498f70c81fc722bf232947155fcd711b9a2fe4ee40896324102b96220f2c53db955cdcdb28a698a2d0abe1cb3eb65701874b071902dfd8a7b9c8e1a9e753b3a50cd465f72d86517b601d5cecb5f54ff74b93a59b8a8268791ddd7a2e0065c2db776dbb9d512eb1025fc563a102ebf5201630040906d26a6e4ce4254e357571ac5efe476aa9d47ac987b8dda658c6ae1acc52b55d72d3fe9529dc3f9ee6075ce69fea0558abc0085e44eebc2b8179f5175e65cf80d5ac8eedd3a7034cb0868ce8fdc6aa2734557ca218b0579ad85ec1c3ef30dc696c82a441aa666243b780379
2024-11-06 22:32:37,182 DEBUG STREAM b'IHDR' 16 13
2024-11-06 22:32:37,183 DEBUG STREAM b'IDAT' 41 6472
2024-11-06 22:32:54,151 INFO Hash value (hex): aa339cad51a6da1fb89278882b482e200760dbf9474c2267de8a25e7f1afb483
2024-11-06 22:32:54,152 INFO Signature verification succeeded.
2024-11-06 22:36:06,981 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-06 22:37:28,932 INFO Key pair found
2024-11-06 22:40:36,298 INFO Key pair found
2024-11-06 22:44:56,873 INFO Key pair found
2024-11-06 22:45:41,568 INFO Key pair found
2024-11-06 22:46:42,819 INFO Key pair found
2024-11-06 22:47:40,455 INFO Key pair found
2024-11-06 22:52:49,482 INFO Key pair found
2024-11-07 16:48:09,275 WARNING Not Found: /favicon.ico
2024-11-07 16:48:34,007 INFO Hash value (hex): aa339cad51a6da1fb89278882b482e200760dbf9474c2267de8a25e7f1afb483
2024-11-07 16:48:34,472 INFO Signature verification succeeded.
2024-11-07 21:00:56,040 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-07 21:01:33,844 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-07 21:03:27,188 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-07 21:03:37,263 WARNING Not Found: /path/to/your/pdf
2024-11-07 21:03:52,454 WARNING Not Found: /path/to/your/pdf
2024-11-07 21:03:57,832 INFO Hash value (hex): aa339cad51a6da1fb89278882b482e200760dbf9474c2267de8a25e7f1afb483
2024-11-07 21:03:57,835 INFO Signature verification succeeded.
2024-11-07 21:03:58,348 WARNING Not Found: /path/to/your/pdf
2024-11-07 21:04:24,059 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-07 21:04:30,025 INFO Hash value (hex): aa339cad51a6da1fb89278882b482e200760dbf9474c2267de8a25e7f1afb483
2024-11-07 21:04:30,028 INFO Signature verification succeeded.
2024-11-07 21:05:02,649 INFO Hash value (hex): aa339cad51a6da1fb89278882b482e200760dbf9474c2267de8a25e7f1afb483
2024-11-07 21:05:02,649 INFO Signature verification succeeded.
2024-11-07 21:10:05,669 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-07 21:10:41,773 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-11-07 21:10:46,164 INFO Hash value (hex): aa339cad51a6da1fb89278882b482e200760dbf9474c2267de8a25e7f1afb483
2024-11-07 21:10:46,167 INFO Signature verification succeeded.
2024-11-07 21:21:19,237 INFO Key pair found
2024-11-07 21:21:40,488 INFO Hash value: aa339cad51a6da1fb89278882b482e200760dbf9474c2267de8a25e7f1afb483
2024-11-07 21:21:40,499 INFO Signature generated (hex): 54fb2d4e0ce3b4fdc67406cf6cd08f775f731eb32cd67c6118316be2ade724dad73de132e0aa1120c7f9471e7445a03566d17aabe3a0ece2a8945618771f6f4d569fe4393de9ebf3b0ee54bcec68471482cb0410c63bf9e23080282d676c5df86bd1a4f7285c253d884d292b8c67b726082631311223594f29ef1d9115fb8fe6e95505544855fca14842144a73d09123f645b6ac5f2de8a12737f5d1fba06dc6ba070520fc730d6285e725331a57b2ae6dfbe72d74a7e81a616311e4f7269191691f80367518b646f436aeb573708a5d06d8f7b21948f38ac70f851720234510fc7bcbb1a660964891366fa4cbb1b3f6a6938a90208e3246c036a7b401b435be
2024-11-07 21:21:40,643 DEBUG STREAM b'IHDR' 16 13
2024-11-07 21:21:40,645 DEBUG STREAM b'IDAT' 41 6472
2024-11-07 21:22:34,522 INFO Hash value (hex): aa339cad51a6da1fb89278882b482e200760dbf9474c2267de8a25e7f1afb483
2024-11-07 21:22:34,523 INFO Signature verification succeeded.
2024-11-07 21:24:58,645 WARNING Not Found: /generate-keypair/SI002
