2024-10-22 10:54:24,033 WARNING Not Found: /files/15/
2024-10-22 10:54:38,347 WARNING Not Found: /files/upload/
2024-10-22 10:55:10,247 INFO F:\Do_An\web1\web1\settings.py changed, reloading.
2024-10-22 10:55:18,027 WARNING Not Found: /files/upload/
2024-10-22 10:55:52,797 INFO F:\Do_An\web1\web1\urls.py changed, reloading.
2024-10-22 10:56:12,844 INFO Signature generated (hex): 7cedc9bc07cc0f7e522be26c0f1247b22509eb573c3c10eeb1c81605b85f4759c5535d2463bd3dce1e82ca702c7528477a3d9043d1457aefc67bc60f5d01dee423e6ad22d39bed834efdddb2b586c06ece04970d7a153a22ae06112b64c2fdb9d496c48be4d3de8969a5f13da054dbf5a8e06e2383faba03d277ec78577e425a3ac31097f15c117620e53548fd726f4fdd5fc24672b819d04d161728a2da26b686adf8e3d9b743c66427835a4378c990971201df9c181a24b294b1e52328b18bbac6fe95cc18f113bc79a23e8c10d2dda2e446b9b66140c27f3d938c31329ada8e345f6efdd301346c4fd9bbda9c38d548909c88a475999c48164f64c48f1338
2024-10-22 11:18:21,859 INFO Signature generated (hex): 615b2fcdfdcfd28d577d16a49bbc424646622f6e8e2440b131d25dac15d5f061b0428a437c3782fb09e106f18953ee4cb8dcf5f22de1d3d231c2635259c801f4c7082024b445172d704824ead66edda10c7109841cb5f45a4f5bd2f5aef474c3709ce7cfe6a21509415769885b537af9d21f89731f9bdc4792dfe949eda00baacd312ae473920b8bf86cfe08ea6aa6830450a1b6c0a13c4ed373fb4368e73493f3b91848c05c66b21e4627af6f0b3b1b2e5ef5be6715de6a9f6bc4317467f96948639a56b38c4c404e6edceed09446d43fb63efcec97845273f2372cdf71c2a2938359870a2ee69352a2f68739e6921edeb25a03c82e90ac5939e79632d1c478
2024-10-22 13:54:26,593 INFO Signature generated (hex): 5c26de1981b6f2766dd62db7fe5b6b0992f6453e00a301885f6d15142ebae334bcac52fda6a17c774014c31c99df2ebdae80ed7a7eed7d16773bdb479d6dcbc3ba8b6cbbe6c401dcff98c52e25b2159e21073989b88f8918d82b1bad1c6d25eda7cecbd57484155becb738014b6ecfc8413cfa5c8586a56ca8e3359d5bdee6dc71d3baef1a6ee711d6bba45c6bc9d5e9623568bd406eac44d33a7a4c63d008c96ac597c4c788b31d299bd856bb7d9c4c653903ef8f9d517f6acf5dac250014a901cf0fdebb983391e7c938bde9d9a2c1db966866e6cacc6ae96456e6dffd374a2a48fa8f19b6defbd1625606fea7e9bf5d54edcefff5a68a733405a83d419798
2024-10-22 13:56:08,429 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-22 13:56:50,792 INFO Extracted signature text from metadata: 5c26de1981b6f2766dd62db7fe5b6b0992f6453e00a301885f6d15142ebae334bcac52fda6a17c774014c31c99df2ebdae80ed7a7eed7d16773bdb479d6dcbc3ba8b6cbbe6c401dcff98c52e25b2159e21073989b88f8918d82b1bad1c6d25eda7cecbd57484155becb738014b6ecfc8413cfa5c8586a56ca8e3359d5bdee6dc71d3baef1a6ee711d6bba45c6bc9d5e9623568bd406eac44d33a7a4c63d008c96ac597c4c788b31d299bd856bb7d9c4c653903ef8f9d517f6acf5dac250014a901cf0fdebb983391e7c938bde9d9a2c1db966866e6cacc6ae96456e6dffd374a2a48fa8f19b6defbd1625606fea7e9bf5d54edcefff5a68a733405a83d419798
2024-10-22 13:56:51,493 INFO Hash value (hex): dc979d4c2b5db8398edead3b4f58c9915f927dd9fac2d8323e557c5811148e5c
2024-10-22 13:56:51,518 ERROR Signature verification failed: 
2024-10-22 13:58:12,511 INFO Extracted signature text from metadata: 5c26de1981b6f2766dd62db7fe5b6b0992f6453e00a301885f6d15142ebae334bcac52fda6a17c774014c31c99df2ebdae80ed7a7eed7d16773bdb479d6dcbc3ba8b6cbbe6c401dcff98c52e25b2159e21073989b88f8918d82b1bad1c6d25eda7cecbd57484155becb738014b6ecfc8413cfa5c8586a56ca8e3359d5bdee6dc71d3baef1a6ee711d6bba45c6bc9d5e9623568bd406eac44d33a7a4c63d008c96ac597c4c788b31d299bd856bb7d9c4c653903ef8f9d517f6acf5dac250014a901cf0fdebb983391e7c938bde9d9a2c1db966866e6cacc6ae96456e6dffd374a2a48fa8f19b6defbd1625606fea7e9bf5d54edcefff5a68a733405a83d419798
2024-10-22 13:58:13,233 INFO Hash value (hex): dc979d4c2b5db8398edead3b4f58c9915f927dd9fac2d8323e557c5811148e5c
2024-10-22 13:58:13,233 ERROR Signature verification failed: 
2024-10-22 13:59:22,511 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-22 13:59:30,087 INFO Extracted signature text from metadata: 5c26de1981b6f2766dd62db7fe5b6b0992f6453e00a301885f6d15142ebae334bcac52fda6a17c774014c31c99df2ebdae80ed7a7eed7d16773bdb479d6dcbc3ba8b6cbbe6c401dcff98c52e25b2159e21073989b88f8918d82b1bad1c6d25eda7cecbd57484155becb738014b6ecfc8413cfa5c8586a56ca8e3359d5bdee6dc71d3baef1a6ee711d6bba45c6bc9d5e9623568bd406eac44d33a7a4c63d008c96ac597c4c788b31d299bd856bb7d9c4c653903ef8f9d517f6acf5dac250014a901cf0fdebb983391e7c938bde9d9a2c1db966866e6cacc6ae96456e6dffd374a2a48fa8f19b6defbd1625606fea7e9bf5d54edcefff5a68a733405a83d419798
2024-10-22 13:59:30,808 INFO Hash value (hex): dc979d4c2b5db8398edead3b4f58c9915f927dd9fac2d8323e557c5811148e5c
2024-10-22 13:59:30,815 ERROR Signature verification failed: 
2024-10-22 14:00:19,999 INFO Hash value: 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-22 14:00:20,000 INFO Signature generated (hex): 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:02:39,441 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:02:40,163 INFO Hash value (hex): dc979d4c2b5db8398edead3b4f58c9915f927dd9fac2d8323e557c5811148e5c
2024-10-22 14:02:40,163 ERROR Signature verification failed: 
2024-10-22 14:04:20,579 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-22 14:04:25,700 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-22 14:04:32,532 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:04:33,216 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-22 14:04:33,223 INFO Signature verification succeeded.
2024-10-22 14:14:16,517 WARNING Not Found: /file/upload_verification
2024-10-22 14:14:35,255 WARNING Not Found: /file/upload-verify/
2024-10-22 14:15:20,110 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:15:20,859 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-22 14:15:20,860 INFO Signature verification succeeded.
2024-10-22 14:50:37,553 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:50:38,311 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-22 14:50:38,313 INFO Signature verification succeeded.
2024-10-22 14:50:48,079 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-22 14:50:48,739 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-22 14:50:48,740 INFO Signature verification succeeded.
2024-10-22 15:16:21,830 WARNING Not Found: /books
2024-10-24 00:17:05,904 WARNING Not Found: /favicon.ico
2024-10-24 00:17:27,603 INFO Extracted signature text from metadata: 10b5e5a38b675c605cb92ee79fbb3ffed4bceec9b7071ef2c07ea0f7409deb9133d76243af41722368e168eeac9fe576897c21e39d5e8572e7c2c892644183cdb3a45e6a497b44867b8bcf76c3d7d6d156173e227d6817d38ffbed1d6f977c84e177c990ed67836ac95e3bccffb986eac323c961948aaf80baf887d7bb52bfe83c9f3e215784b1223c310733d1eed2d50dd45d7fb0748c97f95e98400cbfbc6fb13ab7e6d02bf34095a8739451a0e4bd1ede2ce3c145bf6d5c6e0c56108950cd66236315e0eb929cfc81d2f43b7509b45f0b6e18a919dffcab7699202500f94fc79bef7519c994ff503fed798495397b6498c21de10b481084ceafe64edb5b73
2024-10-24 00:17:28,627 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-24 00:17:28,642 INFO Signature verification succeeded.
2024-10-25 06:25:01,937 WARNING Not Found: /favicon.ico
2024-10-25 06:33:19,500 WARNING Not Found: /books
2024-10-25 06:34:20,648 WARNING Not Found: /books
2024-10-25 06:34:27,828 WARNING Not Found: /books
2024-10-25 06:38:37,909 WARNING Not Found: /books
2024-10-25 06:38:42,202 WARNING Not Found: /files/uploads
2024-10-25 06:50:51,930 INFO F:\Do_An\web1\file\models.py changed, reloading.
2024-10-25 06:51:00,057 INFO F:\Do_An\web1\file\models.py changed, reloading.
2024-10-25 06:54:19,677 INFO F:\Do_An\web1\file\models.py changed, reloading.
2024-10-25 06:54:43,095 INFO F:\Do_An\web1\file\forms.py changed, reloading.
2024-10-25 06:56:44,159 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-25 06:59:35,700 INFO F:\Do_An\web1\file\models.py changed, reloading.
2024-10-25 07:08:20,903 INFO Key pair found
2024-10-25 07:12:56,624 INFO Key pair found
2024-10-25 07:14:11,110 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-25 15:08:46,842 ERROR Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: baseUser.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\users\views.py", line 52, in user_login
    return render(request, 'users/login.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: baseUser.html
2024-10-25 15:24:15,196 INFO Extracted signature text from metadata: 5c26de1981b6f2766dd62db7fe5b6b0992f6453e00a301885f6d15142ebae334bcac52fda6a17c774014c31c99df2ebdae80ed7a7eed7d16773bdb479d6dcbc3ba8b6cbbe6c401dcff98c52e25b2159e21073989b88f8918d82b1bad1c6d25eda7cecbd57484155becb738014b6ecfc8413cfa5c8586a56ca8e3359d5bdee6dc71d3baef1a6ee711d6bba45c6bc9d5e9623568bd406eac44d33a7a4c63d008c96ac597c4c788b31d299bd856bb7d9c4c653903ef8f9d517f6acf5dac250014a901cf0fdebb983391e7c938bde9d9a2c1db966866e6cacc6ae96456e6dffd374a2a48fa8f19b6defbd1625606fea7e9bf5d54edcefff5a68a733405a83d419798
2024-10-25 15:24:17,361 INFO Hash value (hex): 60dd93b31652386ee57161d2b9b9f3b4f418a74191a0b4152974276540ed4ee8
2024-10-25 15:24:17,476 INFO Signature verification succeeded.
2024-10-25 15:24:29,830 INFO No active key pair found
2024-10-25 15:42:11,572 ERROR Signature verification failed: base.html
2024-10-25 15:42:11,685 ERROR Internal Server Error: /files/upload-verify/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 283, in upload_and_verify
    return render(request, 'files/verify_signature.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
2024-10-25 15:42:24,930 ERROR Signature verification failed: baseFile.html
2024-10-25 15:42:24,966 ERROR Internal Server Error: /files/upload-verify/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: baseFile.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 283, in upload_and_verify
    return render(request, 'files/verify_signature.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: baseFile.html
2024-10-25 15:43:01,875 ERROR Signature verification failed: baseFile.html
2024-10-25 15:43:01,908 ERROR Internal Server Error: /files/upload-verify/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: baseFile.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 283, in upload_and_verify
    return render(request, 'files/verify_signature.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: baseFile.html
2024-10-25 15:44:03,598 ERROR Signature verification failed: files/baseUser.html
2024-10-25 15:44:03,687 ERROR Internal Server Error: /files/upload-verify/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: files/baseUser.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 283, in upload_and_verify
    return render(request, 'files/verify_signature.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: files/baseUser.html
2024-10-25 15:44:35,507 ERROR Internal Server Error: /files/upload-verify/
Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: files/baseUser.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Do_An\web1\file\views.py", line 287, in upload_and_verify
    return render(request, 'files/verify_signature.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
  File "C:\Users\SiDT\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: files/baseUser.html
2024-10-25 15:46:47,023 WARNING Not Found: /carts/view
2024-10-26 07:56:32,391 WARNING Not Found: /favicon.ico
2024-10-26 07:57:43,984 INFO Key pair found
2024-10-26 07:57:57,075 INFO Hash value: e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-10-26 07:57:57,090 INFO Signature generated (hex): 47c1ffe289884a9ececbaa1041cbd25ff1d5395d9a74d3f1c7e2020040366180ef397c033050008c5d38d814fd4e1292ea3875c3ce42da1b9f565986ee83e4e0b5d0cfd6d9cd8390b552faf47765d8ce21a0e4a50c7bd563eef5d179e472cfbf59dbe3a2161e45f0985387dbbf25a044b97cf108f63fc6b4a05ab978aff9f330659e2fa9a25ee77bfb39ab31b63c1044e049d1c110665ee9386070fa4dde7d93c6f60c87904d160662c696bb376544f207d9902475b61b682853cf55d3641fc97cc6c2a8918e4c647e7ba9fe7c19918b97ff93c4adf0eb9a724252d66f33e6c712dc8254352b7770883aa74601490bc94fabb1ddba04f188e5344ef0907ce8b2
2024-10-26 07:59:00,373 WARNING Not Found: /favicon.ico
2024-10-26 07:59:33,523 INFO Extracted signature text from metadata: 47c1ffe289884a9ececbaa1041cbd25ff1d5395d9a74d3f1c7e2020040366180ef397c033050008c5d38d814fd4e1292ea3875c3ce42da1b9f565986ee83e4e0b5d0cfd6d9cd8390b552faf47765d8ce21a0e4a50c7bd563eef5d179e472cfbf59dbe3a2161e45f0985387dbbf25a044b97cf108f63fc6b4a05ab978aff9f330659e2fa9a25ee77bfb39ab31b63c1044e049d1c110665ee9386070fa4dde7d93c6f60c87904d160662c696bb376544f207d9902475b61b682853cf55d3641fc97cc6c2a8918e4c647e7ba9fe7c19918b97ff93c4adf0eb9a724252d66f33e6c712dc8254352b7770883aa74601490bc94fabb1ddba04f188e5344ef0907ce8b2
2024-10-26 07:59:33,894 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-10-26 07:59:33,907 INFO Signature verification succeeded.
2024-10-26 08:02:52,121 INFO Extracted signature text from metadata: 47c1ffe289884a9ececbaa1041cbd25ff1d5395d9a74d3f1c7e2020040366180ef397c033050008c5d38d814fd4e1292ea3875c3ce42da1b9f565986ee83e4e0b5d0cfd6d9cd8390b552faf47765d8ce21a0e4a50c7bd563eef5d179e472cfbf59dbe3a2161e45f0985387dbbf25a044b97cf108f63fc6b4a05ab978aff9f330659e2fa9a25ee77bfb39ab31b63c1044e049d1c110665ee9386070fa4dde7d93c6f60c87904d160662c696bb376544f207d9902475b61b682853cf55d3641fc97cc6c2a8918e4c647e7ba9fe7c19918b97ff93c4adf0eb9a724252d66f33e6c712dc8254352b7770883aa74601490bc94fabb1ddba04f188e5344ef0907ce8b2
2024-10-26 08:02:52,498 INFO Hash value (hex): e6e9465395afe2369fe8596fe498011ec4753a64492fb18ab5ed3fbc492c0127
2024-10-26 08:02:52,499 INFO Signature verification succeeded.
2024-10-26 08:18:08,693 INFO Hash value: 305d107c951de8a54de771d68a786d883b7510eebacfba3d922ede25625be71f
2024-10-26 08:18:08,695 INFO Signature generated (hex): 300d987a3b4e7a433b62df947f34e26d943507fb02e251db413cf56f6bcfd9bdf7991a064b1fd30c7efd08aefb3c55025b7449fa8da4409af222da30f9379497e382c461fe5139cf6a6dcf7d5e8cf23aea21a72c1de4994678cff85e65bbf41009745861b69f717aedaa4842d853ce3397c6c10d56d530f294e8f37b8093292834c151f3199c7ab910a2206468664d0ce1ac135955694cf159392214747e639bbcaccb1375934c754ac60e54b2d0234fd52b5fc5f3a6f1d1f34eb04a61641514e5c904b41049e8278ce3a1cc3cfcd28e47a21879445a8df520d3f6cc7320293deb5aa6630ba78b368139eed480bb13f4f0e123866f1a95d73b63e07da0c5dabc
2024-10-26 08:19:18,996 INFO Key pair found
2024-10-26 08:19:33,383 INFO Hash value: 305d107c951de8a54de771d68a786d883b7510eebacfba3d922ede25625be71f
2024-10-26 08:19:33,385 INFO Signature generated (hex): 82e36ff5333d51b24de957fb42df90bfe26ccd705f6a7d9be1678d3e517897d6e65188236d96734a0e43a5f741fc4942e237fcd485d5027614ccbfe6cbbeba1e9629fe731382c4a04a5631b3e011668bb8911214fefce0c807db29c928f4459cd673b780008dfd37fbcaefce5d07b63f010e624380cb0cb8cc655daf6d74b97ea079af5e9a9125571c5690c49766a1a0fdaf6c604d9f713a88597e450af03d4d642a91cc69d1ce0b75e6a394ddb403fd16aa63c7dd245a7bf304ed89c019998919c83faf957aa170772790f067122a1a41592d06bed91ca26248e5d5f577a8a9e675d77a7da30a94fdeadb44783c3d5fadd311bd7b436474ad262a62666995b4
2024-10-26 08:20:05,042 INFO Extracted signature text from metadata: 300d987a3b4e7a433b62df947f34e26d943507fb02e251db413cf56f6bcfd9bdf7991a064b1fd30c7efd08aefb3c55025b7449fa8da4409af222da30f9379497e382c461fe5139cf6a6dcf7d5e8cf23aea21a72c1de4994678cff85e65bbf41009745861b69f717aedaa4842d853ce3397c6c10d56d530f294e8f37b8093292834c151f3199c7ab910a2206468664d0ce1ac135955694cf159392214747e639bbcaccb1375934c754ac60e54b2d0234fd52b5fc5f3a6f1d1f34eb04a61641514e5c904b41049e8278ce3a1cc3cfcd28e47a21879445a8df520d3f6cc7320293deb5aa6630ba78b368139eed480bb13f4f0e123866f1a95d73b63e07da0c5dabc
2024-10-26 08:20:05,048 INFO Hash value (hex): 305d107c951de8a54de771d68a786d883b7510eebacfba3d922ede25625be71f
2024-10-26 08:20:05,049 INFO Signature verification succeeded.
2024-10-26 08:20:56,402 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-26 08:21:43,367 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-26 08:21:51,909 INFO F:\Do_An\web1\file\views.py changed, reloading.
2024-10-26 08:22:22,597 INFO Key pair found
2024-10-26 08:22:27,235 INFO Hash value: 305d107c951de8a54de771d68a786d883b7510eebacfba3d922ede25625be71f
2024-10-26 08:22:27,238 INFO Signature generated (hex): 5b9c2cc664b6d3c60d5dba41966f5e4bef2c2a2b4bfd3c0ede18a2aec14feaa75f6ba7dde7b947f8c7db743833cd86632327d0470b998f580ec78ad50b5bd0fe02795dcd3929d9aca1faba70adfe3452fab71dc71c0b3c5aa481fc7d2d25502b52b971cdd38670eb0fd0e1066fe927d43389837d1974aa23ccacf53af2e165b4a856aed670f17338ccd1c26de83c64921dc6f1304bf8c4b0a38554aae0538b75772a93f49fb9c1ba51072cc1f152af5d3fbc16a005c77b6740f3c1f7150e6e5e5a0a436efadb20de21ddabccf90783d43e9ab403d0bed2e256788a64fd6260cf856785497002488ba4be53d1bab1d6f3b2a08bbc9c23af3cce09991c3a5c688b
2024-10-26 22:54:47,409 WARNING Not Found: /favicon.ico
2024-10-26 22:56:29,695 INFO Key pair found
